import unittest
import pytest
from build123d import *
from ocp_addons.tessellator import *
import numpy as np


class DirectApiTestCase(unittest.TestCase):
    def assertTupleAlmostEquals(self, first, second, places=6, msg=None):
        """Check Tuples"""
        self.assertEqual(len(second), len(first))
        for i, j in zip(second, first):
            self.assertAlmostEqual(i, j, places, msg=msg)

    def assertTupleOfTupleAlmostEquals(self, first, second, places=6, msg=None):
        """Check Tuples"""
        self.assertEqual(len(second), len(first))
        for i, j in zip(second, first):
            self.assertTupleAlmostEquals(i, j, places, msg=msg)

    def assertVectorAlmostEquals(self, first, second, places=6, msg=None):
        second_vector = Vector(second)
        self.assertAlmostEqual(first.X, second_vector.X, places, msg=msg)
        self.assertAlmostEqual(first.Y, second_vector.Y, places, msg=msg)
        self.assertAlmostEqual(first.Z, second_vector.Z, places, msg=msg)


class TestSerializer3D(DirectApiTestCase):

    def test_serializer_simple_shape(self):
        shape = Box(10, 10, 10)
        result = tessellate(shape.wrapped, 0.01)
        self.assertTupleAlmostEquals(
            result.vertices,
            np.array(
                [
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                ],
                dtype=np.float32,
            ),
        )
        self.assertTupleAlmostEquals(
            result.triangles,
            np.array(
                [
                    1,
                    2,
                    0,
                    1,
                    3,
                    2,
                    5,
                    4,
                    6,
                    5,
                    6,
                    7,
                    11,
                    8,
                    9,
                    11,
                    10,
                    8,
                    15,
                    13,
                    12,
                    15,
                    12,
                    14,
                    19,
                    16,
                    17,
                    19,
                    18,
                    16,
                    23,
                    21,
                    20,
                    23,
                    20,
                    22,
                ],
                dtype=np.int32,
            ),
        )

        self.assertTupleAlmostEquals(
            result.normals,
            np.array(
                [
                    -1.0,
                    -0.0,
                    0.0,
                    -1.0,
                    -0.0,
                    0.0,
                    -1.0,
                    -0.0,
                    0.0,
                    -1.0,
                    -0.0,
                    0.0,
                    1.0,
                    0.0,
                    -0.0,
                    1.0,
                    0.0,
                    -0.0,
                    1.0,
                    0.0,
                    -0.0,
                    1.0,
                    0.0,
                    -0.0,
                    -0.0,
                    -1.0,
                    -0.0,
                    -0.0,
                    -1.0,
                    -0.0,
                    -0.0,
                    -1.0,
                    -0.0,
                    -0.0,
                    -1.0,
                    -0.0,
                    0.0,
                    1.0,
                    0.0,
                    0.0,
                    1.0,
                    0.0,
                    0.0,
                    1.0,
                    0.0,
                    0.0,
                    1.0,
                    0.0,
                    -0.0,
                    -0.0,
                    -1.0,
                    -0.0,
                    -0.0,
                    -1.0,
                    -0.0,
                    -0.0,
                    -1.0,
                    -0.0,
                    -0.0,
                    -1.0,
                    0.0,
                    0.0,
                    1.0,
                    0.0,
                    0.0,
                    1.0,
                    0.0,
                    0.0,
                    1.0,
                    0.0,
                    0.0,
                    1.0,
                ],
                dtype=np.float32,
            ),
        )
        self.assertTupleAlmostEquals(
            result.segments,
            np.array(
                [
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                ],
                dtype=np.float32,
            ),
        )
        self.assertTupleAlmostEquals(
            result.obj_vertices,
            np.array(
                [
                    -5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    -5.0,
                    5.0,
                    5.0,
                    -5.0,
                    -5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    5.0,
                    -5.0,
                ],
                dtype=np.float32,
            ),
        )

        self.assertTupleAlmostEquals(
            result.edge_types,
            np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.int32),
        )
        self.assertTupleAlmostEquals(
            result.face_types, np.array([0, 0, 0, 0, 0, 0], dtype=np.int32)
        )
        self.assertTupleAlmostEquals(
            result.segments_per_edge,
            np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=np.int32),
        )
        self.assertTupleAlmostEquals(
            result.triangles_per_face, np.array([2, 2, 2, 2, 2, 2], dtype=np.int32)
        )
