name: Create Python Wheel and Repair

on:
  workflow_dispatch

jobs:
  build:
    name: Build for python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-22.04' ] #, 'macos-11', 'macos-14', 'windows-2019' ] # macos-14 is arm64
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    steps:

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml # located in same dir, by default
          environment-name: ocp-addons # required by micromamba
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install Linux Dependencies (x86_64)
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        shell: bash -l {0}
        run: |
          sudo apt-get update
          sudo apt-get install freetype* libfreetype6-dev libgl1-mesa-glx
          micromamba install -c conda-forge gxx_linux-64=12
          pip install auditwheel patchelf
          micromamba info
          micromamba list

      - name: Build Wheel # TODO: make/add cross-platform for Win especially
        shell: bash -l {0}
        run: |
          python -m build -n

      - name: Repair Linux Wheel (x86_64) # TODO: eliminate hardcoded GLIBC ver
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        shell: bash -l {0}
        run: |
          auditwheel repair --plat manylinux_2_35_x86_64 dist/ocp_addons-*.whl

      - name: Test Repaired Wheel # TODO: make/add cross-platform, also check if all deps are installed correctly by micromamba env update command
        shell: bash -l {0}
        run: |
          micromamba deactivate
          micromamba create --name ocpaddonstest python=${{ matrix.python-version }} --file env.yml --yes
          micromamba activate ocpaddonstest
          micromamba info --envs
          ls wheelhouse/*
          pip install wheelhouse/ocp_addons*.whl
          micromamba list
          python -c "import ocp_addons;print('ocp_addons imported successfully')"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ocp_addons-${{ matrix.os }}-cp${{ matrix.python-version }}
          path: wheelhouse/*.whl
      
